[theme]
base = "light"

[server]
headless = true

[client]
showSidebarNavigation = false

[layout]
default = "centered"

[browser]
gatherUsageStats = false

[global]
pageTitle = "PlanIA Edu – Asistente Pedagógico con IA"
favicon = "assets/logo.png"



